In [106]:
""""This notebook provides an overview of frequently used numpy module commands
along with an example of how to split train test data for machine learning models"""

import numpy as np
import random as r

x = np.array([[1,2,3],[4,5,6]])
print("{}--- ,Ndim = {}, Shape = {}, Size = {},dtype = {}".format(x,x.ndim,x.shape,x.size,x.dtype))


[[1 2 3]
 [4 5 6]]--- ,Ndim = 2, Shape = (2, 3), Size = 6,dtype = int64


In [75]:
np.save('nptest',x)
y = np.load('nptest.npy')
print(y)

[[1 2 3]
 [4 5 6]]


In [76]:
#use np filler functions
a = np.zeros((2,3))
print(a)

a = np.ones((4,3))
print(a)

a = np.identity(4)
print(a)

a = np.full((2,4),8)
print(a)

a = np.diag([5,7,11])
print(a)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[8 8 8 8]
 [8 8 8 8]]
[[ 5  0  0]
 [ 0  7  0]
 [ 0  0 11]]


In [77]:
x = np.arange(0,15,2)
print(x)
print(type(x))

[ 0  2  4  6  8 10 12 14]
<class 'numpy.ndarray'>


In [78]:
#reshape
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [79]:
#random fill
x = np.random.random((2,3))
print(x)

x = np.random.randint(1,12,(2,3))
print(x)

x = np.random.normal(0,0.1,(100,100))
print("{} - {} - {}".format(x.max(),x.min(),x.mean()))

[[0.18499329 0.09745892 0.43034167]
 [0.41014144 0.29337645 0.55064777]]
[[ 2 10 10]
 [ 3  3  5]]
0.36971982306994466 - -0.32911674677971553 - -0.0002621169442840679


In [80]:
oned = np.array([1,2,3])
print(oned)
oned = np.append(oned,[6,7,8])
print(oned)
oned = np.delete(oned,5)
print(oned)
oned = np.insert(oned,1,[2,2])
print(oned)


twod = np.array([[10,11,12],[13,14,15]])
print(twod)
twod = np.append(twod,[[16,17,18]],axis=0)
print(twod)
twod = np.append(twod,[[1],[2],[3]],axis=1)
print(twod)
twod = np.insert(twod,2,[[6,5,4]],axis=1)
print(twod)




[1 2 3]
[1 2 3 6 7 8]
[1 2 3 6 7]
[1 2 2 2 3 6 7]
[[10 11 12]
 [13 14 15]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[10 11 12  1]
 [13 14 15  2]
 [16 17 18  3]]
[[10 11  6 12  1]
 [13 14  5 15  2]
 [16 17  4 18  3]]


In [81]:
#slicing arrays and deep copy
x = np.arange(25).reshape(5,5)
print(x)

s = np.copy(x[1:3,2:])
print(s)

s[1,0] = 100
print(s)
print(x)

#print diagnoal elements of numpy array
print("Diag\n", np.diag(x))
print("Diag Above\n", np.diag(x,k=1))
print("Diag Be;low\n", np.diag(x,k=-1))


#Vertially stack the x array

y = np.array([5,6,7,8,9])
x = np.vstack((x,y))
print(x)

#print unique array elements
print(np.unique(x))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 7  8  9]
 [12 13 14]]
[[  7   8   9]
 [100  13  14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Diag
 [ 0  6 12 18 24]
Diag Above
 [ 1  7 13 19]
Diag Be;low
 [ 5 11 17 23]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [ 5  6  7  8  9]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [86]:
#boolean select and set operators
a = np.arange(20).reshape(4,5)
print(a)
print(a[(a>10) | (a<2)])

one = np.arange(10)
two = np.arange(11)
print(np.intersect1d(one,two))
print(np.setdiff1d(two,one))

b = np.random.randint(1,25,size=(4,4))
print(b)
print("Sorted \n", np.sort(b,axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]
[10]
[[23 14 22  3]
 [13  9 16  7]
 [21 10 11 11]
 [ 7 23 20 21]]
Sorted 
 [[ 7  9 11  3]
 [13 10 16  7]
 [21 14 20 11]
 [23 23 22 21]]


In [93]:
#broadcasting

a = np.array([1,2,3,4]).reshape(2,2)
print(a)
b = np.array([5,6,7,8]).reshape(2,2)
print(b)


#arthmetic operations
print(a+1)
print(a+b)

#statistical operations
print("Mean\n" , np.mean(a,axis=0))
print("Std\n" , a.std(axis=0))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[2 3]
 [4 5]]
[[ 6  8]
 [10 12]]
Mean
 [2. 3.]
Std
 [1. 1.]


In [95]:
#Mean Normalization

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0,5001,size=(1000,20))

# print the shape of X
print(X)

[[3018 4117 4268 ... 1181 3030 1149]
 [  56 3285 3567 ... 2164 1370  559]
 [ 699  146  571 ... 2299 1380 2352]
 ...
 [4973 1478 3656 ...  815 4029 1127]
 [2514 4425 4906 ... 4047  994 4591]
 [ 638 4572  178 ...  915 4581 4044]]


In [99]:
# Average of the values in each column of X
ave_cols = np.mean(X, axis=0)
print("{} \n {} \n {} \n".format(type(ave_cols),ave_cols.shape, ave_cols))

# Standard Deviation of the values in each column of X
std_cols = np.std(X, axis = 0)
print("{} \n {} \n {} \n".format(type(std_cols),std_cols.shape, std_cols))

# Mean normalize X actually Z scores..
X_norm = (X-ave_cols)/std_cols
print(X_norm)

<class 'numpy.ndarray'> 
 (20,) 
 [2454.509 2511.988 2420.488 2523.465 2557.6   2493.224 2519.739 2539.969
 2506.617 2537.028 2555.978 2488.656 2576.293 2463.789 2568.875 2377.955
 2453.855 2546.603 2450.514 2399.727] 

<class 'numpy.ndarray'> 
 (20,) 
 [1416.02152523 1462.00094797 1457.078492   1404.70610406 1463.18061701
 1450.21303946 1417.56082299 1428.09858905 1489.27783516 1476.03603114
 1471.7763198  1464.83273641 1438.50512726 1459.48647218 1425.78219353
 1427.1845252  1451.39806875 1461.20070059 1425.21043422 1433.47016588] 

[[ 0.39793957  1.09781871  1.2679564  ... -0.93457593  0.4065968
  -0.87251694]
 [-1.69383654  0.52873564  0.78685672 ... -0.26184151 -0.75814348
  -1.28410555]
 [-1.2397474  -1.6183218  -1.26931254 ... -0.16945174 -0.75112697
  -0.03329473]
 ...
 [ 1.7785683  -0.70724168  0.84793785 ... -1.18505487  1.10754592
  -0.88786431]
 [ 0.04201278  1.30848889  1.70581888 ...  1.02682472 -1.02196417
   1.52864918]
 [-1.28282584  1.40903602 -1.53903034 ... -1.11661

In [102]:
# Print the average of all the values of X_norm
print(np.mean(X_norm))
# Print the average of the minimum value in each column of X_norm
print(X_norm.min(axis=0).mean())


# Print the average of the maximum value in each column of X_norm
print(X_norm.max(axis=0).mean())

-1.2789769243681803e-17
-1.7243906730023393
[-1.72773433 -1.71750094 -1.65981998 -1.79501249 -1.74523908 -1.71438536
 -1.77399019 -1.77506582 -1.68310905 -1.71474676 -1.736662   -1.69552191
 -1.79025639 -1.67852806 -1.7975221  -1.66618609 -1.69068366 -1.74007787
 -1.71449348 -1.67127789]
1.7287722629811615


In [103]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices =np.random.permutation(X_norm.shape[0])
print(row_indices)

[408 219 564 625 921 137 574 884 188 416 417 518 668  74 255 239 636 252
 242 332 107 868 280 244 538 961 719 109 774 383 312 210  68 827 906 582
 241 483 579  61  54 889  53 389 286 516 758 524 117 131 940 745 589 324
 804 505 298 994 861 139 966 830 850 721 386 132 112 193 350 116  14 552
 998 205 805 596 769 910 347 714 665 264 357 345 813 420 892 521 310 177
 893  21 233  84 471 101 677 828 348  50  57  31 425 896 396 335  38 191
 544 615 422  98 527 652 224 909 653 397 201 465  93 797 952 680 898 163
 166 442 443 227 479 710 679 262   9  26  92 553 959 455  35 841 733 336
 903 375 973 369 922 882 435 678 728  23 988 168 234 173 212 812 997  76
 627 427 740 726 304 528 871 706  25 647 343 523   5 144 337 778 730  29
 289  24 380 330 174 874 379 474 816 870 927 561 796 590 613 587 992 344
 243 691 248 477 925 429 533 439 807 700 707 473 551 844 182 829 482 363
 676 206 395 965 684 803 490 781  83 847 955 319 683 436 135 156 306 352
 571 140  89 934 376 401 309 159 891 835 125 412 64

In [105]:
# Create a Training Set
sixty = int(len(X_norm)*0.6)
eighty = int(len(X_norm)*0.8)

# Create a Training Set
X_train = X_norm[row_indices[:sixty],:]

# Create a Cross Validation Set
X_crossVal = X_norm[row_indices[sixty:eighty],:]

# Create a Test Set
X_test =X_norm[row_indices[eighty:],:]

# Print the shape of X_train
print(X_train.shape)

# Print the shape of X_crossVal
print(X_crossVal.shape)

# Print the shape of X_test
print(X_test.shape)


(600, 20)
(200, 20)
(200, 20)
